/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Aliases {
  alias: string;
  aliasKey: string;
  notePath: string;
}

export interface Assets {
  assetPath: string;
  notePath: string;
}

export interface Backlinks {
  alias: string | null;
  fragmentKind: string | null;
  fragmentValue: string | null;
  kind: string | null;
  posFrom: number | null;
  posTo: number | null;
  sourcePath: string | null;
  targetPath: string | null;
  targetRaw: string | null;
  wikiSyntax: string | null;
}

export interface BlockBacklinks {
  alias: string | null;
  blockId: string | null;
  claimCount: string | null;
  posFrom: number | null;
  posTo: number | null;
  sourcePath: string | null;
  targetOrdinal: string | null;
  targetPath: string | null;
  targetPosFrom: string | null;
  targetPosTo: string | null;
  targetRaw: string | null;
  wikiSyntax: string | null;
}

export interface BlockEmbedPlaces {
  alias: string | null;
  blockId: string | null;
  embedOrdinal: string | null;
  posFrom: number | null;
  posTo: number | null;
  sourcePath: string | null;
  targetOrdinal: string | null;
  targetPath: string | null;
  targetRaw: string | null;
}

export interface BlockKeys {
  blockId: string | null;
  claimCount: string | null;
  notePath: string | null;
  ordinal: string | null;
  posFrom: string | null;
  posTo: string | null;
}

export interface Blocks {
  blockId: string | null;
  breadcrumbs: Generated<string>;
  markdown: string;
  notePath: string;
  ordinal: number;
  posFrom: number;
  posTo: number;
  text: string;
}

export interface BlocksFts {
  context: string | null;
  notePath: string | null;
  noteTitle: string | null;
  ordinal: string | null;
  text: string | null;
}

export interface BlocksFtsConfig {
  k: string;
  v: string | null;
}

export interface BlocksFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  id: Generated<number | null>;
}

export interface BlocksFtsData {
  block: Buffer | null;
  id: Generated<number | null>;
}

export interface BlocksFtsDocsize {
  id: Generated<number | null>;
  sz: Buffer | null;
}

export interface BlocksFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface ChatConversations {
  createdMs: number;
  id: string;
  title: string;
  updatedMs: number;
}

export interface ChatMessages {
  attachments: string;
  conversationId: string;
  createdMs: number;
  id: string;
  parts: string;
  responseMessages: string;
  seq: number;
  userText: string;
}

export interface EmbeddingChunks {
  contentHash: string;
  heading: string | null;
  id: Generated<number | null>;
  modelId: string;
  notePath: string;
  posFrom: number;
  posTo: number;
  text: string;
}

export interface IndexMeta {
  key: string;
  value: string;
}

export interface Links {
  alias: string | null;
  fragmentKind: string | null;
  fragmentValue: string | null;
  kind: string;
  posFrom: number;
  posTo: number;
  sourcePath: string;
  targetBaseKey: string | null;
  targetKey: string;
  targetRaw: string;
  wikiSyntax: string | null;
}

export interface NoteEmails {
  email: string;
  emailKey: string;
  notePath: string;
}

export interface NoteKeys {
  claimCount: string | null;
  key: string | null;
  notePath: string | null;
}

export interface Notes {
  dailyDate: string | null;
  fileHash: string;
  gistStale: Generated<number>;
  gistUrl: string | null;
  hasConflict: Generated<number>;
  id: string | null;
  isPinned: Generated<number>;
  isPrivate: Generated<number>;
  kind: Generated<string>;
  mtime: Generated<number>;
  path: string;
  pinnedOrder: number | null;
  preview: Generated<string>;
  title: string;
  titleKey: string;
  updatedAt: Generated<number>;
}

export interface NoteText {
  notePath: string;
  text: string;
}

export interface SearchFts {
  body: string | null;
  path: string | null;
  title: string | null;
}

export interface Tags {
  notePath: string;
  tag: string;
  tagKey: Generated<string>;
}

export interface Tasks {
  breadcrumbs: Generated<string>;
  checked: number;
  dueDate: string | null;
  markerOffset: number;
  notePath: string;
  raw: string;
  text: string;
}

export interface DB {
  aliases: Aliases;
  assets: Assets;
  backlinks: Backlinks;
  blockBacklinks: BlockBacklinks;
  blockEmbedPlaces: BlockEmbedPlaces;
  blockKeys: BlockKeys;
  blocks: Blocks;
  blocksFts: BlocksFts;
  blocksFtsConfig: BlocksFtsConfig;
  blocksFtsContent: BlocksFtsContent;
  blocksFtsData: BlocksFtsData;
  blocksFtsDocsize: BlocksFtsDocsize;
  blocksFtsIdx: BlocksFtsIdx;
  chatConversations: ChatConversations;
  chatMessages: ChatMessages;
  embeddingChunks: EmbeddingChunks;
  indexMeta: IndexMeta;
  links: Links;
  noteEmails: NoteEmails;
  noteKeys: NoteKeys;
  notes: Notes;
  noteText: NoteText;
  searchFts: SearchFts;
  tags: Tags;
  tasks: Tasks;
}
